import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  map: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    width: '100%',
    height: '100%',
  },
  fab: {
    position: 'absolute',
    margin: 16,
    right: 0,
    bottom: 0,
  },
  bottomControls: {
    left: 10,
    right: 10,
    height: 100,
    width: '90%',
    backgroundColor: 'white',
    borderRadius: 25,
  },
  bottomView: {
    position: 'absolute',
    bottom: 0,
    width: '100%',
    height: 100,
  },
  switchView: {
    position: 'absolute',
    alignContent: 'flex-start',
    margin: 20,
    left: 0,
    bottom: 0,
    height: 40,
    width: 185,
    backgroundColor: 'white',
    borderRadius: 25,
  },
  switch: {
    position: 'absolute',
    left: 10,
    bottom: 5,
  },
  switchText: {
    position: 'absolute',
    left: 60,
    bottom: 10,
  },
  origin: {
    padding: 10,
    flex: 1,
    zIndex: 10,
    width: '100%',
    position: 'absolute',
    opacity: 0.8,
  },
  destination: {
    padding: 10,
    flex: 1,
    zIndex: 3,
    top: 50,
    width: '100%',
    position: 'absolute',
    opacity: 0.8,
  },
  searchBar: {
    position: 'absolute',
    height: 170,
    width: '100%',
    backgroundColor: '#435585',
    zIndex: 1,
    opacity: 0.5,
  },
  searchButton: {
    position: 'absolute',
    top: 105,
    zIndex: 2,
    padding: 10,
  },
  banner: {
    position: 'absolute',
    width: '100%',
    bottom: 0,
    zIndex: 2,
  },
  routeItem: {
    marginBottom: 10,
    marginLeft: 5,
    marginRight: 5,
    padding: 10,
    borderWidth: 2,
    borderColor: '#ccc',
    borderRadius: 5,
  },
  title: {
    fontSize: 18,
    fontWeight: 'bold',
    marginBottom: 5,
  },
  expandedList: {
    marginTop: 10,
    marginBottom: 10,
  },
  stepText: {
    marginLeft: 10,
    width: 80,
  },
  stepView: {
    flexDirection: 'row',
    padding: 10,
  },
  stepInstruction: {
    width: 170,
    textAlign: 'center',
  },
  stepFare: {
    marginLeft: 30,
    width: 40,
  },
  routeContainer: {
    flex: 1,
    flexDirection: 'row',
    width: '100%',
    height: '100%',
  },
  filterItem: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  centeredView: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 22,
  },
  modalView: {
    margin: 20,
    backgroundColor: 'white',
    borderRadius: 20,
    padding: 35,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
  },
  items: {
    marginTop: 20,
    marginBottom: 20,
  },
  screenView: {
    height: '100%',
  },
  welcomeLogo: {
    height: 250,
    width: 250,
  },
  bannerView: {
    height: '50%',
    width: '100%',
    alignItems: 'center',
    justifyContent: 'center',
  },
  loginView: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  loginHeader: {
    fontSize: 30,
    marginBottom: 20,
  },
  logInForm: {
    width: 200,
    borderWidth: 1,
    borderRadius: 25,
    padding: 20,
    margin: 5,
  },
  errorMsgAuth: {
    color: 'red',
  },
  markerView: {
    backgroundColor: 'pink',
    padding: 4,
    borderRadius: 25,
  },
});
